-- 最後の200個の質問データ (801-1000)

INSERT INTO questions (text, category, growth_score, tags) VALUES

-- 追加の多様な質問 (801-900)
('NFT作品を販売する', 'creativity', 0.6, ARRAY['NFT', 'デジタルアート', 'ブロックチェーン']),
('メタバースで土地を買う', 'finance', 0.5, ARRAY['メタバース', '仮想不動産', '投資']),
('VRChat で交流する', 'relationship', 0.4, ARRAY['VRChat', 'メタバース', '交流']),
('Discord サーバー運営', 'relationship', 0.5, ARRAY['Discord', 'コミュニティ', '運営']),
('Twitch 配信者になる', 'creativity', 0.6, ARRAY['Twitch', '配信', 'ゲーム']),
('TikTok でバズる動画作り', 'creativity', 0.5, ARRAY['TikTok', 'バズ', '動画']),
('Instagram リール投稿', 'creativity', 0.5, ARRAY['Instagram', 'リール', 'SNS']),
('Pinterest でボード作成', 'creativity', 0.4, ARRAY['Pinterest', 'ボード', 'アイデア']),
('LinkedIn で人脈作り', 'relationship', 0.7, ARRAY['LinkedIn', 'ビジネス', '人脈']),
('Clubhouse で議論', 'relationship', 0.5, ARRAY['Clubhouse', '音声', '議論']),
('ポッドキャスト配信', 'creativity', 0.6, ARRAY['ポッドキャスト', '音声', '配信']),
('Spotify プレイリスト作成', 'creativity', 0.4, ARRAY['Spotify', '音楽', 'プレイリスト']),
('Apple Music で DJ', 'creativity', 0.4, ARRAY['Apple Music', 'DJ', '音楽']),
('Kindle 本を出版', 'creativity', 0.6, ARRAY['Kindle', '電子書籍', '出版']),
('Audible ナレーター', 'creativity', 0.6, ARRAY['Audible', 'オーディオブック', 'ナレーション']),
('Uber ドライバー', 'finance', 0.5, ARRAY['Uber', 'ドライバー', '副業']),
('Airbnb ホスト', 'finance', 0.6, ARRAY['Airbnb', '民泊', '副業']),
('TaskRabbit で仕事', 'finance', 0.5, ARRAY['TaskRabbit', 'ギグワーク', '副業']),
('ココナラで出品', 'finance', 0.5, ARRAY['ココナラ', 'スキル販売', '副業']),
('ランサーズで受注', 'finance', 0.6, ARRAY['ランサーズ', 'フリーランス', '仕事']),
('クラウドワークス活用', 'finance', 0.6, ARRAY['クラウドワークス', '在宅', '仕事']),
('BASE でネットショップ', 'finance', 0.6, ARRAY['BASE', 'EC', 'ネットショップ']),
('STORES 開業', 'finance', 0.6, ARRAY['STORES', 'EC', '開業']),
('Shopify ストア運営', 'finance', 0.7, ARRAY['Shopify', 'EC', 'グローバル']),
('Amazon FBA ビジネス', 'finance', 0.7, ARRAY['Amazon', 'FBA', '物販']),
('楽天市場出店', 'finance', 0.6, ARRAY['楽天', 'EC', '出店']),
('メルカリせどり', 'finance', 0.5, ARRAY['メルカリ', 'せどり', '転売']),
('ヤフオク転売', 'finance', 0.5, ARRAY['ヤフオク', 'オークション', '転売']),
('PayPay フリマ活用', 'finance', 0.4, ARRAY['PayPay', 'フリマ', '売買']),
('ラクマで販売', 'finance', 0.4, ARRAY['ラクマ', 'フリマ', '販売']),
('StockX でスニーカー転売', 'finance', 0.5, ARRAY['StockX', 'スニーカー', '転売']),
('BOOTH で同人誌販売', 'creativity', 0.5, ARRAY['BOOTH', '同人誌', '創作']),
('pixiv FANBOX 運営', 'creativity', 0.5, ARRAY['pixiv', 'FANBOX', 'クリエイター']),
('Patreon でサポート獲得', 'creativity', 0.6, ARRAY['Patreon', 'サポート', 'クリエイター']),
('Buy Me a Coffee 設置', 'creativity', 0.4, ARRAY['寄付', 'サポート', 'クリエイター']),
('GitHub スポンサー', 'career', 0.6, ARRAY['GitHub', 'スポンサー', 'オープンソース']),
('Stack Overflow 貢献', 'career', 0.7, ARRAY['Stack Overflow', 'プログラミング', '貢献']),
('Qiita 記事投稿', 'career', 0.6, ARRAY['Qiita', '技術記事', '共有']),
('Zenn で技術書執筆', 'career', 0.6, ARRAY['Zenn', '技術書', '執筆']),
('Dev.to で英語記事', 'career', 0.7, ARRAY['Dev.to', '英語', '技術記事']),
('Medium でブログ', 'creativity', 0.5, ARRAY['Medium', 'ブログ', '執筆']),
('はてなブログ運営', 'creativity', 0.5, ARRAY['はてな', 'ブログ', '日記']),
('WordPress サイト構築', 'career', 0.6, ARRAY['WordPress', 'サイト', 'Web']),
('Wix でHP作成', 'creativity', 0.4, ARRAY['Wix', 'HP', 'ノーコード']),
('Notion でナレッジベース', 'learning', 0.6, ARRAY['Notion', 'ナレッジ', '整理']),
('Obsidian で知識管理', 'learning', 0.6, ARRAY['Obsidian', '知識', 'PKM']),
('Roam Research 活用', 'learning', 0.6, ARRAY['Roam', '思考', 'ツール']),
('Anki で暗記学習', 'learning', 0.6, ARRAY['Anki', '暗記', 'SRS']),
('Duolingo で語学', 'learning', 0.6, ARRAY['Duolingo', '語学', 'アプリ']),
('Coursera で学位取得', 'learning', 0.8, ARRAY['Coursera', 'オンライン', '学位']),
('Udemy 講師になる', 'career', 0.7, ARRAY['Udemy', '講師', 'オンライン']),
('edX で修了証', 'learning', 0.7, ARRAY['edX', 'MOOC', '修了証']),
('Khan Academy で基礎学習', 'learning', 0.6, ARRAY['Khan Academy', '基礎', '無料']),
('Codecademy でコーディング', 'learning', 0.6, ARRAY['Codecademy', 'プログラミング', '学習']),
('LeetCode で競プロ', 'learning', 0.7, ARRAY['LeetCode', '競プロ', 'アルゴリズム']),
('HackerRank チャレンジ', 'learning', 0.7, ARRAY['HackerRank', 'プログラミング', 'チャレンジ']),
('Kaggle コンペ参加', 'career', 0.8, ARRAY['Kaggle', 'データサイエンス', 'コンペ']),
('AtCoder で茶色コーダー', 'learning', 0.6, ARRAY['AtCoder', '競プロ', 'レート']),
('TopCoder 参戦', 'learning', 0.7, ARRAY['TopCoder', '競プロ', 'グローバル']),
('CodeForces レート上げ', 'learning', 0.7, ARRAY['CodeForces', '競プロ', 'レート']),
('Figma でUI設計', 'creativity', 0.7, ARRAY['Figma', 'UI', 'デザイン']),
('Sketch マスター', 'creativity', 0.6, ARRAY['Sketch', 'デザイン', 'Mac']),
('Adobe XD 習得', 'creativity', 0.6, ARRAY['Adobe XD', 'プロトタイプ', 'デザイン']),
('Framer でインタラクション', 'creativity', 0.6, ARRAY['Framer', 'インタラクション', 'デザイン']),
('Principle アニメーション', 'creativity', 0.6, ARRAY['Principle', 'アニメーション', 'UI']),
('After Effects マスター', 'creativity', 0.7, ARRAY['After Effects', 'モーション', '映像']),
('Premiere Pro 編集', 'creativity', 0.7, ARRAY['Premiere', '動画編集', 'Adobe']),
('DaVinci Resolve 習得', 'creativity', 0.7, ARRAY['DaVinci', '動画編集', 'カラー']),
('Final Cut Pro 編集', 'creativity', 0.6, ARRAY['Final Cut', '動画編集', 'Mac']),
('Logic Pro で作曲', 'creativity', 0.7, ARRAY['Logic Pro', '作曲', 'Mac']),
('Ableton Live で DJ', 'creativity', 0.6, ARRAY['Ableton', 'DJ', '音楽']),
('FL Studio ビート作成', 'creativity', 0.6, ARRAY['FL Studio', 'ビート', '音楽']),
('Cubase 録音', 'creativity', 0.6, ARRAY['Cubase', '録音', 'DAW']),
('Pro Tools ミキシング', 'creativity', 0.7, ARRAY['Pro Tools', 'ミキシング', 'プロ']),
('GarageBand 入門', 'creativity', 0.5, ARRAY['GarageBand', '音楽', '入門']),
('Photoshop 極める', 'creativity', 0.7, ARRAY['Photoshop', '画像編集', 'Adobe']),
('Illustrator マスター', 'creativity', 0.7, ARRAY['Illustrator', 'ベクター', 'デザイン']),
('InDesign でDTP', 'creativity', 0.6, ARRAY['InDesign', 'DTP', '出版']),
('Lightroom で写真管理', 'creativity', 0.6, ARRAY['Lightroom', '写真', '現像']),
('Procreate でイラスト', 'creativity', 0.6, ARRAY['Procreate', 'iPad', 'イラスト']),
('Clip Studio Paint', 'creativity', 0.6, ARRAY['クリスタ', 'マンガ', 'イラスト']),
('Blender で3DCG', 'creativity', 0.7, ARRAY['Blender', '3D', 'CG']),
('Maya モデリング', 'creativity', 0.7, ARRAY['Maya', '3D', 'プロ']),
('ZBrush スカルプト', 'creativity', 0.7, ARRAY['ZBrush', 'スカルプト', '3D']),
('Cinema 4D 習得', 'creativity', 0.7, ARRAY['Cinema 4D', '3D', 'モーション']),
('Houdini エフェクト', 'creativity', 0.8, ARRAY['Houdini', 'VFX', 'エフェクト']),
('Substance Painter', 'creativity', 0.6, ARRAY['Substance', 'テクスチャ', '3D']),
('Marvelous Designer', 'creativity', 0.6, ARRAY['Marvelous', '服', '3D']),
('TouchDesigner VJ', 'creativity', 0.6, ARRAY['TouchDesigner', 'VJ', 'ビジュアル']),
('Processing アート', 'creativity', 0.6, ARRAY['Processing', 'アート', 'プログラミング']),
('p5.js クリエイティブ', 'creativity', 0.6, ARRAY['p5.js', 'Web', 'アート']),
('OpenFrameworks', 'creativity', 0.7, ARRAY['OpenFrameworks', 'C++', 'アート']),
('Max/MSP 音響', 'creativity', 0.6, ARRAY['Max/MSP', '音響', 'プログラミング']),
('Pure Data 実験', 'creativity', 0.6, ARRAY['Pure Data', '音', 'オープンソース']),
('VVVV ビジュアル', 'creativity', 0.6, ARRAY['VVVV', 'ビジュアル', 'ノード']),
('Grasshopper 建築', 'creativity', 0.7, ARRAY['Grasshopper', '建築', 'パラメトリック']),
('Rhino モデリング', 'creativity', 0.7, ARRAY['Rhino', '3D', '建築']),
('SketchUp 設計', 'creativity', 0.6, ARRAY['SketchUp', '3D', '建築']),
('AutoCAD 図面', 'career', 0.7, ARRAY['AutoCAD', 'CAD', '図面']),
('Revit BIM', 'career', 0.7, ARRAY['Revit', 'BIM', '建築']),

-- 最後の100個 (901-1000)
('朝ヨガを習慣化', 'health', 0.8, ARRAY['ヨガ', '朝', '健康']),
('夜ランニング習慣', 'health', 0.7, ARRAY['ランニング', '夜', '運動']),
('階段を使う生活', 'health', 0.6, ARRAY['階段', '運動', '日常']),
('自転車通勤', 'health', 0.7, ARRAY['自転車', '通勤', 'エコ']),
('徒歩通勤に変更', 'health', 0.7, ARRAY['徒歩', '通勤', '健康']),
('電車で座らない', 'health', 0.5, ARRAY['電車', '立つ', '筋力']),
('エスカレーター使わない', 'health', 0.6, ARRAY['階段', 'エスカレーター', '運動']),
('エレベーター使わない', 'health', 0.6, ARRAY['階段', 'エレベーター', '運動']),
('歩数計で1万5千歩', 'health', 0.7, ARRAY['歩数', '目標', '健康']),
('活動量計で管理', 'health', 0.6, ARRAY['活動量計', 'データ', '健康']),
('Apple Watch で健康管理', 'health', 0.6, ARRAY['Apple Watch', 'ヘルスケア', 'デバイス']),
('Fitbit で睡眠分析', 'health', 0.6, ARRAY['Fitbit', '睡眠', '分析']),
('Garmin でトレーニング', 'health', 0.7, ARRAY['Garmin', 'トレーニング', 'GPS']),
('WHOOP で回復度測定', 'health', 0.6, ARRAY['WHOOP', '回復', 'アスリート']),
('Oura Ring で体調管理', 'health', 0.6, ARRAY['Oura', '指輪', '健康']),
('血圧を毎日測定', 'health', 0.6, ARRAY['血圧', '測定', '健康管理']),
('体温を記録', 'health', 0.5, ARRAY['体温', '記録', '健康']),
('心拍変動を測定', 'health', 0.6, ARRAY['心拍', 'HRV', 'ストレス']),
('血糖値モニタリング', 'health', 0.6, ARRAY['血糖値', 'モニター', '健康']),
('遺伝子検査を受ける', 'health', 0.5, ARRAY['遺伝子', '検査', '予防']),
('アレルギー検査', 'health', 0.5, ARRAY['アレルギー', '検査', '体質']),
('腸内フローラ検査', 'health', 0.6, ARRAY['腸内フローラ', '検査', '健康']),
('人間ドック年1回', 'health', 0.7, ARRAY['人間ドック', '検診', '予防']),
('脳ドック受診', 'health', 0.6, ARRAY['脳ドック', 'MRI', '検査']),
('歯科検診3ヶ月毎', 'health', 0.7, ARRAY['歯科', '検診', '予防']),
('眼科検診年1回', 'health', 0.6, ARRAY['眼科', '検診', '視力']),
('整体に月2回通う', 'health', 0.5, ARRAY['整体', '体調', 'メンテナンス']),
('鍼灸治療を受ける', 'health', 0.5, ARRAY['鍼灸', '東洋医学', '治療']),
('カイロプラクティック', 'health', 0.5, ARRAY['カイロ', '骨格', '矯正']),
('マッサージ週1回', 'health', 0.4, ARRAY['マッサージ', 'リラックス', '疲労']),
('足つぼマッサージ', 'health', 0.4, ARRAY['足つぼ', 'リフレ', '健康']),
('リンパマッサージ', 'health', 0.5, ARRAY['リンパ', 'マッサージ', 'デトックス']),
('アロママッサージ', 'health', 0.5, ARRAY['アロマ', 'マッサージ', 'リラックス']),
('タイ古式マッサージ', 'health', 0.5, ARRAY['タイ古式', 'マッサージ', 'ストレッチ']),
('ロミロミマッサージ', 'health', 0.4, ARRAY['ロミロミ', 'ハワイ', 'マッサージ']),
('アーユルヴェーダ', 'health', 0.5, ARRAY['アーユルヴェーダ', 'インド', '伝統医学']),
('ホメオパシー', 'health', 0.4, ARRAY['ホメオパシー', '代替医療', '自然']),
('フラワーレメディ', 'health', 0.4, ARRAY['フラワーレメディ', '花', '感情']),
('クリスタルヒーリング', 'health', 0.3, ARRAY['クリスタル', 'パワーストーン', 'ヒーリング']),
('レイキヒーリング', 'health', 0.4, ARRAY['レイキ', 'エネルギー', 'ヒーリング']),
('気功を習う', 'health', 0.6, ARRAY['気功', '中国', 'エネルギー']),
('太極拳を毎朝', 'health', 0.6, ARRAY['太極拳', '朝', '健康']),
('呼吸法を実践', 'health', 0.7, ARRAY['呼吸', '呼吸法', 'リラックス']),
('ウィムホフメソッド', 'health', 0.6, ARRAY['ウィムホフ', '呼吸', '冷水']),
('ブレスワーク', 'health', 0.6, ARRAY['ブレスワーク', '呼吸', '瞑想']),
('マインドフルネス瞑想', 'health', 0.8, ARRAY['マインドフルネス', '瞑想', '今ここ']),
('ヴィパッサナー瞑想', 'health', 0.7, ARRAY['ヴィパッサナー', '瞑想', '観察']),
('超越瞑想TM', 'health', 0.6, ARRAY['超越瞑想', 'TM', 'マントラ']),
('慈悲の瞑想', 'health', 0.7, ARRAY['慈悲', '瞑想', '思いやり']),
('歩行瞑想', 'health', 0.6, ARRAY['歩行', '瞑想', 'マインドフル']),
('食事瞑想', 'health', 0.6, ARRAY['食事', '瞑想', 'マインドフル']),
('ボディスキャン瞑想', 'health', 0.6, ARRAY['ボディスキャン', '瞑想', '身体']),
('音浴・サウンドバス', 'health', 0.5, ARRAY['音浴', 'サウンド', 'ヒーリング']),
('シンギングボウル', 'health', 0.5, ARRAY['シンギングボウル', '音', 'チベット']),
('クリスタルボウル', 'health', 0.5, ARRAY['クリスタルボウル', '音', 'ヒーリング']),
('ゴングバス体験', 'health', 0.5, ARRAY['ゴング', '音', 'リラックス']),
('森林浴を週1回', 'health', 0.6, ARRAY['森林浴', '自然', 'リラックス']),
('海水浴で健康', 'health', 0.5, ARRAY['海水浴', '海', '健康']),
('日光浴で健康維持', 'health', 0.5, ARRAY['日光浴', '太陽', 'ビタミンD']),
('月光浴でリラックス', 'health', 0.4, ARRAY['月光浴', '月', 'リラックス']),
('星空観察で癒し', 'health', 0.5, ARRAY['星空', '観察', '癒し']),
('アーシング実践', 'health', 0.5, ARRAY['アーシング', '裸足', '大地']),
('グラウンディング', 'health', 0.5, ARRAY['グラウンディング', '地に足', '安定']),
('デジタルデトックス週末', 'lifestyle', 0.7, ARRAY['デジタルデトックス', 'スマホ', '休息']),
('SNS断ち1ヶ月', 'lifestyle', 0.7, ARRAY['SNS', 'デトックス', '離脱']),
('テレビなし生活', 'lifestyle', 0.6, ARRAY['テレビ', 'なし', 'シンプル']),
('新聞だけで情報収集', 'lifestyle', 0.5, ARRAY['新聞', 'アナログ', '情報']),
('ラジオ生活', 'lifestyle', 0.5, ARRAY['ラジオ', '音声', 'シンプル']),
('手書き日記365日', 'lifestyle', 0.7, ARRAY['手書き', '日記', '継続']),
('万年筆で手紙', 'lifestyle', 0.6, ARRAY['万年筆', '手紙', 'アナログ']),
('カリグラフィー習得', 'creativity', 0.6, ARRAY['カリグラフィー', '文字', 'アート']),
('ペン字練習', 'learning', 0.5, ARRAY['ペン字', '美文字', '練習']),
('習字教室に通う', 'learning', 0.6, ARRAY['習字', '書道', '日本文化']),
('俳画を描く', 'creativity', 0.6, ARRAY['俳画', '俳句', '絵']),
('水墨画を学ぶ', 'creativity', 0.6, ARRAY['水墨画', '墨', '東洋']),
('日本画を描く', 'creativity', 0.7, ARRAY['日本画', '岩絵具', '伝統']),
('油絵を始める', 'creativity', 0.7, ARRAY['油絵', '絵画', 'アート']),
('水彩画教室', 'creativity', 0.6, ARRAY['水彩', '絵画', '透明感']),
('アクリル画制作', 'creativity', 0.6, ARRAY['アクリル', '絵画', '現代']),
('パステル画を描く', 'creativity', 0.5, ARRAY['パステル', '絵画', '柔らかい']),
('色鉛筆画を極める', 'creativity', 0.5, ARRAY['色鉛筆', '絵画', '細密']),
('鉛筆デッサン', 'creativity', 0.6, ARRAY['デッサン', '鉛筆', '基礎']),
('木炭デッサン', 'creativity', 0.6, ARRAY['木炭', 'デッサン', '明暗']),
('クロッキー習慣', 'creativity', 0.6, ARRAY['クロッキー', 'スケッチ', '速写']),
('風景スケッチ旅', 'creativity', 0.6, ARRAY['スケッチ', '風景', '旅']),
('人物画を学ぶ', 'creativity', 0.7, ARRAY['人物画', 'ポートレート', '絵画']),
('抽象画に挑戦', 'creativity', 0.6, ARRAY['抽象画', 'アート', '表現']),
('コラージュ作品', 'creativity', 0.5, ARRAY['コラージュ', 'アート', '組み合わせ']),
('インスタレーション', 'creativity', 0.7, ARRAY['インスタレーション', '空間', 'アート']),
('パフォーマンスアート', 'creativity', 0.7, ARRAY['パフォーマンス', 'アート', '身体']),
('ランドアート制作', 'creativity', 0.7, ARRAY['ランドアート', '自然', 'アート']),
('ストリートアート', 'creativity', 0.6, ARRAY['ストリート', 'アート', '都市']),
('グラフィティアート', 'creativity', 0.5, ARRAY['グラフィティ', 'スプレー', 'アート']),
('壁画を描く', 'creativity', 0.7, ARRAY['壁画', 'ミューラル', '大作']),
('チョークアート', 'creativity', 0.5, ARRAY['チョーク', 'アート', '黒板']),
('サンドアート', 'creativity', 0.5, ARRAY['砂', 'アート', '一時的']),
('氷の彫刻に挑戦', 'creativity', 0.6, ARRAY['氷', '彫刻', '儚い']),
('バルーンアート', 'creativity', 0.4, ARRAY['バルーン', '風船', 'パフォーマンス']),
('オリガミアート', 'creativity', 0.5, ARRAY['折り紙', '日本', 'アート']),
('切り絵作家', 'creativity', 0.6, ARRAY['切り絵', '紙', 'アート']),
('影絵パフォーマンス', 'creativity', 0.6, ARRAY['影絵', 'パフォーマンス', '光と影']);