-- RLSを無効化（開発段階では一旦無効に）
ALTER TABLE questions DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE habits DISABLE ROW LEVEL SECURITY;
ALTER TABLE avoid_list DISABLE ROW LEVEL SECURITY;